apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.registry }}/frontend:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: {{ .Values.services.frontend.port }}
  type: LoadBalancer
